# Generated by Django 5.1.4 on 2024-12-30 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_probe', models.CharField(max_length=255)),
                ('interested_probe', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('higher_education', models.CharField(blank=True, max_length=255, null=True)),
                ('pass_out_year', models.CharField(blank=True, max_length=4, null=True)),
                ('university_college', models.CharField(blank=True, max_length=255, null=True)),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='prober.personinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='prober.personinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProberProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('enquiry_timestamp', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_error_message', models.TextField(blank=True, null=True)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('whatsapp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_error_message', models.TextField(blank=True, null=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prober.address')),
                ('education', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prober.education')),
                ('person_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prober.personinfo')),
                ('streem_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prober.streemdetails')),
            ],
        ),
    ]
